/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_my_project_test_jni_JNIUtils */

#ifndef _Included_com_my_project_test_jni_JNIUtils
#define _Included_com_my_project_test_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_project_test_jni_JNIUtils
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_my_1project_test_1jni_JNIUtils_getName
  (JNIEnv *, jobject,jstring);

#ifdef __cplusplus
}
#endif
#endif
